travis:
  secure:
    BINSTAR_TOKEN: XrMfTzZsjXHScCOPm/CQ8Dc7Z2g7T0Nxf4OAu4pfATKZXZ/QY44xX5LrDodFLEtxX7aua0eGDiuBkLMGLZNvCNiuQ1J7gweaKHoO5WT97BT3jGs8eju7RP70rlhWsvW97CZizmpjF3EIqjEZPtCkGsaBCHHcnoDLIE0eLzOA1makFFHw3tyaKLWyyuy22Q4oMl1B765pVFmRTaPTlzQDl+1bpbhgNyAXXu831CrSCT/y8cTeNzteLoE5h/iB3dZixRNWxdVIZ/f55pG1zPwg2Qt+/UFoXk6gg8qYlvyl5HEoqMBjv45FdKUGJnr8lHdk1eMUyj9MWynQ0WQS0vr2zG1FOBgRlaW31DQNhNPynquJo7RPqaJd3F/Mcro9GNa+L0gFzDWczOSfhckZEW9IxwEZpP4tlxQOR1xdr+O/mKDENavPWJTMRpY51oodK1LZeAq1jipSnrn/1Pui907ERFYa8RhWbr0uJO+nUoOJXb3BPP0UdpxGaeOIzV5hZmYninsz3kHjyzYczAyMxQg1x/Rr7WiYx4gIHc408rj2kKkRODM2P1CcgFecsPMFGYA4OnZs1jUxMbPXHgFnXkLFo+n4/s0c8/pl/S8EFhGUBqqFC4vFUiD7MVxTU7ctRNDUDWGaPGIqDJUz681qjGUbZsWYH0L/VzITN4exDBm2muA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
