travis:
  secure:
    BINSTAR_TOKEN: QtFgskRtaxiXj3pt3/8TMkITx5DMSCNmOAwagDMkFWuILmI+Hxla//9umrW/kb3HtsjOy9ZuLZccBv5AAQCsYfP4EIylG4huGIp6zMSsbDtqD4bH7TYkjf93qAl1Y7Q5GVIpqmdVvGyQczgv2u//Ge9vsukxCnMCxme6CqORMfjlXNprwnV/MeWBowT3w3AILFQFOSD7MZgqwKBGV8JgacDPk+X+d5TO1f4A3D75VCJ5RBlIcnrSxxQk6lZDLnZp0VVu1cpMsdkH1DqPMDpojiytY3kQ0qpHhwijTJUlOej77So1/BGp+zdhtPjjnRVttjDdQBrUGnmQkESWrunyh7ixBH+gljJmjGMRlGAJhP+Cs1t2/6s5Bwbws8bXt+FfGEi8B2nkLpTqx7yyOFn9tRoWMzrKwXEE2xIFddXdLuXbfDEa79AuGTQMurYYOmTG+JEbSnX4NiA8DNBxfybh8mM1It17OZtMb4/3jFJZUqAdpMYP7QK6lwLcpEn7J8nPpX0bu8cEv4A6/jKiZnqD0zsz2ZNM04DfhvUjsSuuzL9LKxWn571JACfzHX1l1/sFH86KQl+MxuCRYIAI7UNsPR50JODd4FwBnUp8aLDs0fAF/aMI7uE4+jwCRS2FmcZwBksOCcwwKOIxftl0QWJ6WvV00If8LjZrcQYLR08RmLA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
